_welcome:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo

# next routes needed for the InPageEditDemoBundle
_ipe_demo_odme:
    pattern:  /ipe_demo/odme
    defaults: { _controller: AcmeDemoBundle:IpeDemo:odme }

_ipe_demo_odme_without_controller:
    path: /ipe_demo/odme_without_controller
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'AcmeDemoBundle:IpeDemo:static_odme.html.twig'

_ipe_demo_odgsmec:
    pattern:  /ipe_demo/odgsmec
    defaults: { _controller: AcmeDemoBundle:IpeDemo:odgsmec }

_ipe_demo_wysiwyg:
    pattern:  /ipe_demo/wysiwyg
    defaults: { _controller: AcmeDemoBundle:IpeDemo:wysiwyg }


_ipe_demo_odgsmec_without_controller:
    path: /ipe_demo/odgsmec_without_controller
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'AcmeDemoBundle:IpeDemo:static_odgsmec.html.twig'